---
# role: qemu
# file: molecule/dev/molecule.yml

dependency:
  name: "galaxy"
  options:
    role-file: "${MOLECULE_PROJECT_DIRECTORY}/collections.yml"
    requirements-file: "${MOLECULE_PROJECT_DIRECTORY}/collections.yml"
driver:
  name: "podman"
provisioner:
  name: "ansible"
  config_options:
    defaults:
      forks: 8
      interpreter_python: "auto_silent"
      allow_world_readable_tmpfiles: true
      callbacks_enabled: "ansible.builtin.default"
      callback_result_format: "yaml"
      remote_tmp: "/tmp/.ansible/tmp"
      display_ok_hosts: false
      display_skipped_hosts: false
      show_task_path_on_failure: true
    ssh_connection:
      pipelining: true
  log: true
  playbooks:
    converge: "../resources/playbooks/converge.yml"
    verify: "../resources/playbooks/verify.yml"
    prepare: "../resources/playbooks/prepare.yml"
  inventory:
    group_vars:
      all:
        __qemu_test_native_only: "{{ ansible_facts.distribution == 'AlmaLinux' }}"
        qemu_architectures: "{{ lookup('ansible.builtin.env', 'QEMU_ARCHITECTURES', default=([ansible_facts.architecture]\
          \ if __qemu_test_native_only else ['x86_64', 'aarch64']) | to_json) | from_json }}"
        qemu_storage_modules: "{{ lookup('ansible.builtin.env', 'QEMU_STORAGE_MODULES', default='[\"curl\", \"rbd\"]' if __qemu_test_native_only\
          \ else '[\"curl\", \"iscsi\", \"nfs\", \"rbd\", \"ssh\"]') | from_json }}"
        qemu_display_modules: "{{ lookup('ansible.builtin.env', 'QEMU_DISPLAY_MODULES', default=('[]' if ansible_facts.architecture\
          \ != 'x86_64' else '[\"egl-headless\"]') if __qemu_test_native_only else ('[\"gtk\", \"spice\", \"egl-headless\"\
          ]' if ansible_facts.os_family == 'Suse' else '[\"gtk\", \"sdl\", \"spice\", \"egl-headless\"]')) | from_json }}"
        qemu_uefi: "{{ lookup('ansible.builtin.env', 'QEMU_UEFI', default='true') | bool }}"
        qemu_add_packages:
          - "file"
verifier:
  name: "ansible"
scenario:
  test_sequence:
    - "dependency"
    - "destroy"
    - "syntax"
    - "create"
    - "prepare"
    - "check"
    - "converge"
    - "idempotence"
    - "check"
    - "verify"
    - "destroy"
  name: "dev"
platforms:
  - name: "almalinux-latest-qemu"
    image: "docker.io/jomrr/molecule-almalinux:latest"
    pre_build_image: true
    override_command: false
    systemd: "true"
  - name: "debian-latest-qemu"
    image: "docker.io/jomrr/molecule-debian:latest"
    pre_build_image: true
    override_command: false
    systemd: "true"
  - name: "fedora-latest-qemu"
    image: "docker.io/jomrr/molecule-fedora:latest"
    pre_build_image: true
    override_command: false
    systemd: "true"
  - name: "opensuse-leap-latest-qemu"
    image: "docker.io/jomrr/molecule-opensuse-leap:latest"
    pre_build_image: true
    override_command: false
    systemd: "true"
  - name: "opensuse-tumbleweed-latest-qemu"
    image: "docker.io/jomrr/molecule-opensuse-tumbleweed:latest"
    pre_build_image: true
    override_command: false
    systemd: "true"
  - name: "ubuntu-latest-qemu"
    image: "docker.io/jomrr/molecule-ubuntu:latest"
    pre_build_image: true
    override_command: false
    systemd: "true"
